### ISSUE TITLE
Rework FCU Autopilot Display and Buttons

### ISSUE THREAD

**Issue by scotflieger** [joeherwig/A32nx-LINDA-aircraft-module#20]
The FCU autopilot display and buttons need to be reworked so that display better represents the VC cockpit display. It is proposed to reuse existing code used for LINDA Aerosoft A3XX module. This will incorporate a Timer() and a number of display functions. A number of the button functions require work as not all are working reliably.

**Comment by joeherwig** [comment]
closed by 12ca6899cff57c5fc2685d3b36583c478b02e872
