### ISSUE TITLE
Change VRI FCU/MCP Configurations to Default

### ISSUE THREAD

**Issue by scotflieger** [joeherwig/A32nx-LINDA-aircraft-module#23]
The released LINDA modules builds should not overwrite users existing configuration files. The configuration files for the VRI FCU/MCP should have the extension **.default**. When first run LINDA will check for existing configuration files and when not found will copy the .default file to a **.lua** version. This affects **config-mcp.default**, **config-mcp2.default** and **config-mcp2a.default**.

The **.default** configuration files can be built automatically from the installed files using the LINDA module build function. The procedure is as follows:

- With required aircraft selected, double-click on the **Maintenance** link,
- Click on the **Create MCP Config Files** button. 
- Click on the **Create MCP Default Files** button.
- Under **Export Aircraft Module**, click on **Select Target Folder** and pick destination folder (eg. Documents).
- Click on **Export New Module** button.

**Comment by scotflieger** [comment]
Scotflieger-patch-6 provides config-mcp2a.default to match Issue #20 pull request.

**Comment by joeherwig** [comment]
My https://github.com/joeherwig/A32nx-LINDA-aircraft-module/blob/main/A32nx/LINDA-CFG/aircrafts/FBW%20A320/config-mcp2a.lua.downloaded is imho not good enough to go for a real .default, but probably at least a start.
Do you have good ones?

**Comment by joeherwig** [comment]
Already renamed the config-mcp2a.lua delivered with the release to config-mcp2a.default
