### ISSUE TITLE
About the APU button

### ISSUE THREAD

**Issue by zhensanmao** [joeherwig/A32nx-LINDA-aircraft-module#4]
Happy New Year, I installed the A32nx LINDA module, but APU MASTER, APU START, and APU BLEED have no effect. What is the reason and what should I do?

**Comment by scotflieger** [comment]
The APU Master and Start functions were successfully tested. The APU Bleed initially failed until the extra space between 'function' and the function name was removed.

There should only be one space. Ensure you have the latest versions of WASM 0.5.5d, FBW A32nx and FSUIPC7 7.2.14. LINDA 4.0.7 also allows users to monitor and modify Lvar values.

**Comment by joeherwig** [comment]
included in 0.10.0
