### ISSUE TITLE
Group System Functions

### ISSUE THREAD

**Issue by scotflieger** [joeherwig/A32nx-LINDA-aircraft-module#49]
By convention the System Functions in an aircraft module should be grouped at the bottom of the module action.lua to avoid use by and confusion to users.

Move InitDsp, A32NX_AP_INFO and A32NX_FLIGHT_INFO functions to bottom and group with InitVars and Timer functions.

**Comment by joeherwig** [comment]
setDimmer is currently also part of that group. Adding that to the end.
