### ISSUE TITLE
Add Overhead APU buttons

### ISSUE THREAD

**Issue by scotflieger** [joeherwig/A32nx-LINDA-aircraft-module#51]
The Overhead APU Master/Start/Bleed buttons can be implemented with the Custom Lvars: A32NX_OVHD_APU_MASTER_SW_PB_IS_ON, A32NX_OVHD_APU_START_PB_IS_ON and A32NX_OVHD_PNEU_APU_BLEED_PB_IS_ON.

**Comment by joeherwig** [comment]
So more a renaming?

Probably we should define logic naming conventions to avoid those confusions and iterations as the users will have to reassign the functions then. That's quite annoying for all of us.

Do you have already some naming conventions?
The ones from FBW really do not make always sense and are same heterogeneous.

**Comment by scotflieger** [comment]
The normal naming convention have used for LINDA should identify the aircraft, panel, sub-panel and system. I appreciate it will require a one-off re-assignment but is easier to follow in the long term. For the MCPs these will be provided by the .default files. How many people do you think are using the FBW to date?
