### ISSUE TITLE
Implement Integral Panel, Flood and Display Knobs

### ISSUE THREAD

**Issue by scotflieger** [joeherwig/A32nx-LINDA-aircraft-module#63]
There is a need to implement the light dimmer knobs for the Integral Panel lights (Overhead, Pedestal and FCU), Flood Lights (Capt and FO) and PFD/ND/MCDU displays.

The FBW Flight Deck API specifies a number of LIGHT POTENTIOMETER:XX MSFS VARs which have not been made available as FSUIPC7 Controls.

**Comment by joeherwig** [comment]
Added documentation into the wiki: https://github.com/joeherwig/A32nx-LINDA-aircraft-module/wiki/lighting-knobs
