### ISSUE TITLE
A32nx-LINDA-aircraft-module 0.10.2, doesn't work,

### ISSUE THREAD

**Issue by zhensanmao** [joeherwig/A32nx-LINDA-aircraft-module#68]
I installed LINDA 4.1.2, installed FSUIPC 7.2.15 and it's registered, installed A32nx-LINDA-aircraft-module 0.10.2, but,  it doesn't work, all the peripheral hardware switch buttons don't work , I am particularly concerned about how the APU MASTER\START\BLEED button of FWB320 should be set

**Comment by scotflieger** [comment]
This is a LINDA Support issue and should be dealt with on the forum.
